### ISSUE TITLE
Files without ODIM codes

### ISSUE THREAD

**Issue by CeciliaNilsson709** [enram/timamp-etl#18]
When trying to run the German data I get stuck because the files don't contain any ODIM codes. The metadata only contains the WMO code... 🤦‍♀️. Is there some way of getting around this so I can process the German files?

**Comment by peterdesmet** [comment]
[Won't someone please think of the metadata?!](https://www.youtube.com/watch?v=Qh2sWSVRrmo) 😭  The radar ids in `attributes$source` are apparently less consistent than the radar_id in the filenames (`seang_vp_20161003T2000Z.h5`), so let's use those instead.

Also, for the German data, the `datetime` in the vp file (e.g. `2016-10-03 02:10:12`) is slightly different than the datetime in the filename (`2016-10-03 02:00:00`), but still within the 15 minutes. To get neat 15 minute intervals, will use the filenames for the datetimes.

All of this makes sense though, as we are already using the filenames to filter on radars and dates. But, it's now extra important to good care of the file names. 😄

**Comment by peterdesmet** [comment]
To make use of this, you'll have to reinstall bioRad:

```
devtools::install_github("enram/bioRad", ref="master")
```

Once https://github.com/adokter/bioRad/issues/38 is accepted, the normal bioRad can be installed again.

**Comment by adokter** [comment]
@peterdesmet I changed vol2bird such that it now stores input and output filename also as an attribute in the .h5 files. However, due to limitations of a Baltrad library used to generate the h5 files, I could only store these attributes under the /how group, not the /what group.

Since accepting pull request adokter/bioRad#38, the filename of the polar volume is stored under attributes$what$vp_filename. For consistency, I would like to change that to attributes$how$filename_vp. But we would have to coordinate to change that simultaneously in vp_processing and bioRad. Let me know when you can change it, than I immediately update bioRad as well.

**Comment by peterdesmet** [comment]
Ok, `$how` makes less sense that `$what`, but we have to use what we can. 😄  I've just updated vp-processing to use that new attribute: its commit hash should appear above. Once you've adapted bioRad, I'll install it again and test to see if everything still works (hope to do that tomorrow morning). I'll then update vp-processing with a pull request.

**Comment by adokter** [comment]
@peterdesmet Sorry took some more time as I needed to fix some other minor issues for this next bioRad release. I've now updated the new attribute, see https://github.com/adokter/bioRad/commit/4f8f5ab99f8305ba9f3ade04b61f0874752c6965

**Comment by peterdesmet** [comment]
Updated in vp-processing: https://github.com/enram/vp-processing/pull/29. Closing issue.
