### ISSUE TITLE
Bird profiles to csv

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#7]
@stijnvanhoey @plieper @adokter rather than to stumble my way around R, I'd rather ask first: have you already done a data transformation similar to this:

## Input vp data

radar_1 / time_1 / dens (can be retrieved from attributes I assume):

```
0      200      400      ...      4800
NA 35.59053 41.27831 ...    NA
```

radar_1 / time_1 / u:

```
0        200        400        ...        4800
NA  -9.421702  -8.746634  ...  NA
```

## Output data

radar | time | altitude | dens | u
-- | -- | -- | -- | --
radar_1 | time_1 | 0 | NA | NA
radar_1 | time_1 | 200 | 35.59053 | -9.421702
radar_1 | time_1 | 400 | 41.27831 | -8.746634
radar_1 | time_1 | ... | ... | ...
radar_1 | time_1 | 4800 | NA | NA
radar_1 | time_2 | ... | ... | ...
radar_2 | time_1 | ... | ... | ...

**Comment by adokter** [comment]
This is what readvp function does in bioRad:
```
library(bioRad)
myvp=readvp(yourfile.h5)
```
To access the table above:
```
myvp$data
```
However I try to avoid people accessing the data structure directly, and have them use the fetch function to extract particular fields, e.g. for the bird density 'dens':
```
fetch(vp, quantity = "dens")
```
This is because of various thresholds applied to the bird density column, in particular the radar cross section and radial velocity standard deviation thresholds that are applied in a 'posthoc' way. Users may change these in bioRad, and then the bird density column 'dens' in this table gets recomputed from column 'eta'.

**Comment by peterdesmet** [comment]
Thanks @adokter 

I was indeed using `fetch`[^1] before, but that way I only access one variable at a time, with altitude bins as columns (and the variable as the row). With `myvp$data` I indeed get it all at once in a data.frame, with the altitude bins as rows and the variables as columns, which is perfect. Since I'm just transforming (i.e. restructuring) data, I think it's fine to use that method rather than fetch.

Next step is to search in myvp$attributes to get the radar name and timestamp, cause I'll need that in my table too.

[^1]: which might have a bug for vplist #4
