### ISSUE TITLE
Which height bins do we want?

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#9]
In the sample files I got from Sweden, there are 25 heights (`HGHT`). From 0 until 4800 (inclusive), each one 200m.

```
0
200
400
600
800
1000
1200
1400
1600
1800
2000
2200
2400
2600
2800
3000
3200
3400
3600
3800
4000
4200
4400
4600
4800
```

## How should we handle these?

* [x] Do all radars have this height range? If not, what height range should we take across all radars (min/max)?
* [x] Should the lower 0-200m band be removed as it will mainly contain clutter?
* [x] Are the heights in sections of 200m for all radars? If not, what height ranges do we have?

## In what bins should we aggregate these?

In TIMAMP, the heights are aggregated several times, in 1, 2, 4, 5, 8 and 19 bins, which you can [select as a user](http://timamp.github.io/timamp/v2/case-eu.html) in the `strata` option. Those bins are defined in `strataOptions` [here](https://github.com/enram/timamp/blob/master/v2/preprocess/eu15a/input/metadata.json).

For a first pass, I'd prefer if we'd stick to one aggregation. So, which height bins do you propose for the flyway data?

**Comment by CeciliaNilsson709** [comment]
In the latest data set Liesbeth processed there are heights from 0 to 3800, all in 200 m bins.  All radars will have all of these height bins, but in many cases they will not all contain data (for example stations with high ground level will of course be missing low altitude data).

Yes, the lowest bin should be excluded, and I think the 3800 m is high enough for all sites, so that would mean including **bins 200 to 3800** (equaling data from 200 to 4000 m asl).

For this large scale analysis I agree that we should not get to much lost in the detailed height distributions, I think **4 bins** would definitely be enough, but I'll run that by the others tomorrow, to make sure they agree.

**Comment by peterdesmet** [comment]
From 200 to 3800 there are 19 heights and although we defined that these should be aggregated in 4 bins, we haven't really defined how those bins should be made. I guess like this:

```
0200 0400 0600 0800 1000
1200 1400 1600 1800 2000
2200 2400 2600 2800 3000
3200 3400 3600 3800
```

In any case, this is not urgent, as the aggregation depends on the type of visualization we will use, and we did not get to that.

**Comment by peterdesmet** [comment]
For the flowviz, the [aggregation](https://github.com/enram/vp-processing/blob/master/src/vp_to_flowviz.Rmd#add-height-bins) is now:

* 200-2000m
* above 2000m
